/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.JOptionPane;
import object.FontSetting;

/**
 *
 * @author ACER
 */
public class AboutPage extends javax.swing.JFrame {

    private Locale currentLocale;

    /**
     * Creates new form AboutPage
     */
    public AboutPage(Locale locale) {
        this.currentLocale = locale;
        initComponents();
        applyLanguage(locale);
    }

    private void applyFont() {
        try {
            FontSetting fs = new FontSetting("CODE2000", 1, 14);
            fs.selectContainer(getContentPane());
        } catch (Exception e) {
            System.err.println("Font Error: " + e.getMessage());
        }
    }
    
    private void applyLanguage(Locale locale) {
        try {
            ResourceBundle rb = ResourceBundle.getBundle("localization/Bundle", locale);
            lblChooseLanguage.setText(rb.getString("AboutPage.lblChooseLanguage.text"));
            lblAboutTitle.setText(rb.getString("AboutPage.lblAboutTitle"));
            lblAboutDescription.setText(rb.getString("AboutPage.lblAboutDescription"));
            setTitle(rb.getString("AboutPage.lblAboutTitle"));
        } catch (Exception e) {
            showError(locale, "error.language");
        }
    }

    private void showError(Locale locale, String key) {
        ResourceBundle rb = ResourceBundle.getBundle("localization/Bundle", locale);
        JOptionPane.showMessageDialog(this, rb.getString(key), rb.getString("error.lblAboutTitle"), JOptionPane.ERROR_MESSAGE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblChooseLanguage = new javax.swing.JLabel();
        cmbChooseLanguage = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        lblAboutTitle = new javax.swing.JLabel();
        lblAboutDescription = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        lblChooseLanguage.setText("Choose language");

        cmbChooseLanguage.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "English", "Indonesian", "Korean", "Japan" }));
        cmbChooseLanguage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbChooseLanguageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(lblChooseLanguage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(cmbChooseLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblChooseLanguage)
                    .addComponent(cmbChooseLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(0, 153, 204));

        lblAboutTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblAboutTitle.setText("About This Application");

        lblAboutDescription.setText("This application is a multilingual GUI systemdesigned with Java Swing.");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblAboutDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(lblAboutTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(lblAboutTitle)
                .addGap(39, 39, 39)
                .addComponent(lblAboutDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbChooseLanguageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbChooseLanguageActionPerformed
                int lang = cmbChooseLanguage.getSelectedIndex();
        switch (lang) {
            case 0:
                currentLocale = new Locale("en", "US");
                break;
            case 1:
                currentLocale = new Locale("in", "ID");
                break;
            case 2:
                currentLocale = new Locale("ko", "KR");
                break;
            case 3:
                currentLocale = new Locale("ja", "JP");
                break;
            default:
                currentLocale = new Locale("en", "US");
                break;
        }
        applyLanguage(currentLocale); // Terapkan ulang bahasa
    }//GEN-LAST:event_cmbChooseLanguageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        Locale defaultLocale = new Locale("en", "US"); 
        java.awt.EventQueue.invokeLater(() -> {
            new AboutPage(defaultLocale).setVisible(true); 
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbChooseLanguage;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblAboutDescription;
    private javax.swing.JLabel lblAboutTitle;
    private javax.swing.JLabel lblChooseLanguage;
    // End of variables declaration//GEN-END:variables
}
